### ISSUE TITLE
Prior art

### ISSUE THREAD

**Issue by tomberek** [icetan/nix-git-ignore-source#1]
How is this different/better than: https://github.com/siers/nix-gitignore  ?

It seems there is a need for this. Perhaps combine efforts? @siers ? Get this included in upstream?

**Comment by icetan** [comment]
This repo is mostly a quick and dirty hack that I've been using for a while and will probably not work with many `.gitignore` files. @siers project is more serious with actual tests.

I will add a link to @siers project in the readme.
